version: '3.9'
services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "9000:80"
    volumes:
      - ../app:/app
    restart: always